reporter: xcode

included:
  - ReSwiftFeedSample
  - ReSwiftFeedSampleTests

excluded:
  - Pods

opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - contains_over_first_not_nil
  - discouraged_optional_boolean
  - empty_count
  - explicit_init
  - fatal_error_message
  - first_where
  - force_unwrapping
  - implicit_return
  - joined_default_parameter
  - literal_expression_end_indentation
  - nimble_operator
  - no_extension_access_modifier
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - private_action
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - vertical_parameter_alignment_on_call

disabled_rules:
  - multiple_closures_with_trailing_closure
  - private_unit_test
  - notification_center_detachment

array_init: error
attributes:
  severity: error
  always_on_same_line: ["@IBAction", "@IBOutlet", "@objc"]
class_delegate_protocol: error
closing_brace: error
closure_end_indentation: error
closure_parameter_position: error
closure_spacing: error
colon:
  severity: error
comma: error
compiler_protocol_init: error
cyclomatic_complexity:
   warning: 6
   error: 6
   ignores_case_statements: true
control_statement: error
discarded_notification_center_observer: error
discouraged_optional_boolean: error
empty_enum_arguments: error
empty_parameters: error
empty_parentheses_with_trailing_closure: error
explicit_init: error
fatal_error_message: error
file_length:
  warning: 300
  error: 300
first_where: error
for_where: error
force_unwrapping: error
function_body_length:
  warning: 100
  error: 100
function_parameter_count:
  warning: 6
  error: 6
identifier_name:
  min_length:
    warning: 0
    error: 0
  max_length:
    warning: 50
    error: 50
  allowed_symbols: ["_"]
implicit_getter: error
implicit_return: error
joined_default_parameter: error
large_tuple:
  warning: 3
  error: 3
leading_whitespace: error
legacy_cggeometry_functions: error
legacy_constant: error
legacy_constructor: error
legacy_nsgeometry_functions: error
line_length:
  warning: 200
  error: 200
  ignores_urls: true
  ignores_function_declarations: true
  ignores_comments: false
literal_expression_end_indentation: error
mark: error
nesting:
  type_level:
    warning: 2
    error: 2
  statement_level:
    warning: 5
    error: 5
nimble_operator: error
notification_center_detachment: error
object_literal:
  severity: error
opening_brace: error
operator_usage_whitespace: error
operator_whitespace: error
overridden_super_call:
  severity: error
private_action:
  severity: error
private_outlet:
  severity: error
  allow_private_set: true
prohibited_super_call:
  severity: error
protocol_property_accessors_order: error
redundant_discardable_let: error
redundant_nil_coalescing: error
redundant_optional_initialization: error
redundant_string_enum_value: error
redundant_void_return: error
return_arrow_whitespace: error
statement_position:
  severity: error
syntactic_sugar: error
todo: warning
trailing_comma: 
  severity: error
trailing_newline: error
trailing_semicolon: error
trailing_whitespace: 
  severity: error
type_body_length:
  warning: 200
  error: 200
type_name:
  min_length:
    warning: 2
    error: 2
  max_length:
    warning: 50
    error: 50
unused_closure_parameter: error
unused_enumerated: error
unused_optional_binding:
  severity: error
valid_ibinspectable: error
vertical_parameter_alignment: error
vertical_whitespace:
  severity: error
vertical_parameter_alignment_on_call: error
void_return: error
weak_delegate: error
